version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: h2-api-johotel
    ports:
      - "9022:8080"   # optional: keep for direct Swagger access in dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      # .NET config via env var mapping:
      ConnectionStrings__DefaultConnection: "Host=ep-damp-grass-a2y11rk5-pooler.eu-central-1.aws.neon.tech;Username=neondb_owner;Password=REPLACE_ME;Database=neondb;sslmode=require"
      Jwt__Issuer: "MyHotelApi"
      Jwt__Audience: "MyHotelFrontend"
      Jwt__SecretKey: "REPLACE_ME_SUPER_SECRET"
      # helps when behind a reverse proxy/https:
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    restart: unless-stopped
    networks:
      - h2-network

  blazor:
    build:
      context: .
      dockerfile: Blazor/Dockerfile
    container_name: h2-blazor-johotel
    ports:
      - "9021:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - h2-network

networks:
  h2-network:
    driver: bridge
