version: "3.8"

services:
  # API Service (ASP.NET Core)
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: h2-api-Johotel
    ports:
      - "9022:8080"                 # host:container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      # Optional override instead of appsettings.json (fill password if you use this):
      # - ConnectionStrings__DefaultConnection=Host=ep-damp-grass-a2y11rk5-pooler.eu-central-1.aws.neon.tech;Username=neondb_owner;Password=YOUR_PASSWORD;Database=neondb;Ssl Mode=Require;Trust Server Certificate=true
    networks:
      - h2-network
    restart: unless-stopped

  # Blazor WASM (served by nginx or ASP.NET static site – whatever your Dockerfile does)
  blazor:
    build:
      context: .
      dockerfile: Blazor/Dockerfile
    container_name: h2-blazor-Johotel
    ports:
      - "9021:80"                   # host:container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiEndpoint=http://localhost:9022/   # important: browser calls the API via host port
    depends_on:
      - api
    networks:
      - h2-network
    restart: unless-stopped

networks:
  h2-network:
    driver: bridge
